In [1]:
from get_probabilities import *
import numpy as np
import pandas as pd

In [6]:
cloze_allword("lawn")

array([0.        , 0.0409066 , 0.00012871, 0.00813118], dtype=float32)

In [7]:
cloze_allword(["lawn", "the", "mow"])

array([0.000000e+00, 5.931186e-04, 7.043716e-06], dtype=float32)

In [8]:
np.array(cloze_allword(parse_text("Colorless green ideas sleep furiously"))) #can probably use something like this to generate probability of each sentence

array([0.0000000e+00, 4.3508870e-04, 1.1648185e-07, 2.7400322e-06,
       2.8559724e-10], dtype=float32)

In [9]:
sen_prob = np.prod(arr[1:])
print(sen_prob)
print(-1*np.log2(sen))

NameError: name 'arr' is not defined

In [6]:
file = open(r'C:\Users\vaj1\Documents\sentencesurprisal\yelp\train.txt', "r", encoding = "utf8")
file_data = file.read()
lines = file_data.splitlines()
file.close()

data = []

#only use senteces that contain the keyword
keyword = "pizza"
for s in lines:
    if keyword in s:
        data.append(s)
data.append("Colorless green ideas sleep furiously .")
data.append("Ideas verdes incoloras duermen furiosamente .")
data.append("Les idées vertes incolores dorment furieusement .")
#data.append("What a nice day !")

In [7]:
for i in range(len(data)):
    data[i] = "ø " + data[i] + " ø"

In [8]:
#print(data)

In [9]:
surprisals = []
data = np.array(data)
for i in data:
    surprisals.append(-(np.sum(np.log2(np.array(cloze_allword(parse_text(i)))[1:-1]))))
ranked_surprisals = np.flip(np.argsort(surprisals))

In [10]:
print(np.where(ranked_surprisals == len(data)-2)[0])

[3]


In [11]:
sen_rankings = []
for i in ranked_surprisals:
    sen_rankings.append(data[i][2:-2])
print(pd.DataFrame(sen_rankings))
with open("GPT-2 Sentence_Rankings", 'w') as f:
    for i in sen_rankings:
        f.write(i + "\n")
    f.close()

                                                      0
0     Les idées vertes incolores dorment furieusement .
1     decidi comer uma pizza , j que eu tava com pou...
2     http : //www.foodiebytes.com/menu/nc/huntersvi...
3         Ideas verdes incoloras duermen furiosamente .
4     i went there because the isthmus annual manual...
...                                                 ...
2143                                            pizza .
2144                                            pizza .
2145                                            pizza .
2146                                            pizza :
2147                                            - pizza

[2148 rows x 1 columns]


In [12]:
print(sen_rankings)

['Les idées vertes incolores dorment furieusement .', 'decidi comer uma pizza , j que eu tava com pouco dinheiro .', 'http : //www.foodiebytes.com/menu/nc/huntersville/tonys-pizza.html', 'Ideas verdes incoloras duermen furiosamente .', 'i went there because the isthmus annual manual said it had great wood-oven pizzas .', "if your from my generation than you can remember ellio 's rectangular frozen pizza .", 'decent neighborhood pizza can be found in morningside at eddies pizza haus .', 'but goldberg looking fellow that brought out pizza and desserts was hauling ass .', "as darren claims , bellisario 's pizza is a shinning knight . ''", 'quality pizza crust , hellava lot better than il fornio and better price !', '( yes i know that reference is french ) so mangia bene at il pizzaillo', 'very unhelpful service and pizzas always arrive 20-30 mins after time given on order .', 'if you like the pizza here , then you will love chefboyardee out-of-the-box pizza .', 'the chef slings a pizza ou

In [13]:
print(np.where(np.array(sen_rankings) == "Colorless green ideas sleep furiously .")[0][0])

25
